All methods that consume messages from NATS must meet the following conditions:

* The method must reside in a class annotated with ann:nats.annotation.NatsListener[].
* The method must be annotated with ann:nats.annotation.Subject[].

NOTE: In order for all of the functionality to work as `designed` in this guide your classes must be compiled with the parameters flag set to `true`.
If your application was created with the Micronaut CLI, then that has already been configured for you.

=== Simple Consumer

The easiest way for defining a producer is the following:

[source,java]
----
    @Subject("my-products")
    public void receive(String name) {
        System.out.println("Got Product - " + name);
    }
----

=== Queue Support

Subscribers may specify queue groups at subscription time. When a message is published to the group NATS will deliver it to a one-and-only-one subscriber.

IMPORTANT: Queue groups do not persist messages. If no listeners are available, the message is discarded.

[source,java]
----
    @Subject(value = "my-products", queue="my-queue")
    public void receive(String name) {
        System.out.println("Got Product - " + name);
    }
----

=== Return Type and RPC

IMPORTANT: If the consumer defines a return type, it automatically will use the RPC logic and will send the return value to the producer

[source,java]
----
    @Subject(value = "my-products")
    public Product receive(String name) {
        return new Product(name);
    }
----
