All properties on the link:{apinats}/io/nats/client/Options.html[Options] are available to be modified, either through configuration or a link:{apimicronaut}context/event/BeanCreatedEventListener.html[BeanCreatedEventListener].

The properties that can be converted from the string values in a configuration file can be configured directly.

include::{includedir}configurationProperties/io.micronaut.nats.connect.NatsConnectionFactoryConfig.adoc[]

NOTE: Without any configuration the defaults in the link:{apinats}/io/nats/client/Options.html[Options] will be used.

TIP: It is also possible to disable the integration entirely with `nats.enabled: false`


== Connections

It is possible to configure multiple connections to the same server, different servers, or a single connection to one of a list of servers.

[configuration]
----
nats:
  server1:
    addresses:
      - "nats://localhost:4222"
    username: guest
    password: guest
  server2:
    addresses:
      - "nats://randomServer:4222"
    username: guest
    password: guest
----

NATS also supports a fail over connection strategy where the first server that connects successfully will be used among a list of servers. To use this option in Micronaut, simply supply a list of `host:port` addresses.

[configuration]
----
nats:
  default:
    addresses:
      - "nats://localhost:4222"
      - "nats://randomServer:4222"
    username: guest
    password: guest
----

IMPORTANT: When the configuration option `nats.servers` is used, no other options underneath `nats` are read; for example `nats.username`.

If you need to setup TLS, it can be configured this way:

[configuration]
----
nats:
  default:
    addresses:
      - "nats://localhost:4222" # <1>
    tls:
      trust-store-path:  /path/to/client.truststore.jks # <2>
      trust-store-password: secret
      certificate-path: /path/to/certificate.crt # <3>
----

<1> You can either use `nats://localhost:4222` or `tls://localhost:4222` as protocol.
<2> You can configure a complete truststore
<3> Or you can use a single certificate for connecting to NATS securely.

If the server requires a client certificate (mutual TLS), configure a key store holding the client certificate and its private key in addition:

[configuration]
----
nats:
  default:
    addresses:
      - "tls://localhost:4222"
    tls:
      trust-store-path: /path/to/client.truststore.jks
      trust-store-password: secret
      key-store-path: /path/to/client.p12 # <1>
      key-store-password: secret # <2>
      key-store-type: PKCS12 # <3>
----

<1> The key store with the client certificate and private key
<2> The password of the key store, also used for the private key
<3> The key store type, defaults to the JVM default key store type

== Further connection options

Besides the options above, all options of the link:{apinats}/io/nats/client/Options.Builder.html[Options.Builder] which can be converted from a configuration value can be set directly underneath the connection. Options without an argument, such as `noRandomize()`, are enabled by setting them to `true`.

[configuration]
----
nats:
  default:
    addresses:
      - "nats://localhost:4222"
    max-pings-out: 5
    no-randomize: true
    request-cleanup-interval: 10s
    reconnect-jitter: 200ms
    max-messages-in-outgoing-queue: 10000
    discard-messages-when-outgoing-queue-full: true
----

include::{includedir}configurationProperties/io.nats.client.Options$Builder.adoc[]

NOTE: Options which require objects at runtime (for example executors, listeners or handlers) can only be set through a link:{apimicronaut}context/event/BeanCreatedEventListener.html[BeanCreatedEventListener] for the `io.micronaut.nats.connect.NatsConnectionFactoryConfig`, using `getBuilder()`.
