This library supports RPC through the usage of link:https://docs.nats.io/nats-concepts/core-nats/reqreply[Request-Reply]. Both blocking and non blocking variations are supported.

The following is an example direct reply to where the consumer is converting the body to upper case and replying with the converted string.

== Client Side

The "client side" in this case starts by publishing a message. A consumer somewhere will then receive the message and reply with a new value.

snippet::io.micronaut.nats.docs.rpc.ProductClient[tags="imports,clazz", project-base="docs-examples/example"]

<1> The send method is blocking and will return when the response is received.
<2> The sendReactive method returns a reactive type that will complete when the response is received. Reactive methods will be executed on the IO thread pool.

IMPORTANT: In order for the publisher to assume RPC should be used instead of just completing when the publish is confirmed, the data type must *not* be `Void`. In both cases above, the data type is `String`.

== Server Side

The "server side" in this case starts with the consumption of a message, and then a new message is published by returning the result

snippet::io.micronaut.nats.docs.rpc.ProductListener[tags="imports,clazz", project-base="docs-examples/example"]

<1> The data from message is injected.
<2> The converted message is returned.

NOTE: If the reply publish fails for any reason, the original message will be rejected.

IMPORTANT: RPC consumer methods must never return a reactive type. Because the resulting publish needs to occur on the same thread and only a single item can be emitted, there is no value in doing so.
