[versions]
micronaut = "5.1.6"
micronaut-platform = "5.0.5"
micronaut-gradle-plugin = "5.0.2"

awaitility = '4.3.0'
bouncycastle = '2.73.11'
nats = '2.26.0'

micronaut-micrometer = "6.0.1"
micronaut-reactor = "4.1.0"
micronaut-rxjava3 = "4.1.0"
micronaut-serde = "3.1.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

jnats = { module = 'io.nats:jnats', version.ref = 'nats'}
bouncycastle-bcprov-lts8on = { module = 'org.bouncycastle:bcprov-lts8on', version.ref = 'bouncycastle' }
awaitility = { module = 'org.awaitility:awaitility', version.ref = 'awaitility' }

micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = "micronaut-reactor" }
micronaut-rxjava3 = { module = 'io.micronaut.rxjava3:micronaut-rxjava3', version.ref = "micronaut-rxjava3"}
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
testcontainers = { module = "org.testcontainers:testcontainers" }

gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

[plugins]
