[versions]
micronaut = "5.0.0-M17"
micronaut-platform = "4.10.10"
micronaut-gradle-plugin = "4.6.2"

awaitility = '4.3.0'
nats = '2.24.1'

micronaut-micrometer = "5.13.2"
micronaut-reactor = "4.0.0-M1"
micronaut-rxjava3 = "3.9.0"
micronaut-serde = "3.0.0-M1"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

jnats = { module = 'io.nats:jnats', version.ref = 'nats'}
awaitility = { module = 'org.awaitility:awaitility', version.ref = 'awaitility' }

micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = "micronaut-reactor" }
micronaut-rxjava3 = { module = 'io.micronaut.rxjava3:micronaut-rxjava3', version.ref = "micronaut-rxjava3"}
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
testcontainers = { module = "org.testcontainers:testcontainers" }

gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

[plugins]
