plugins {
    id 'io.micronaut.build.internal.nats-examples'
    id 'groovy'
}

dependencies {
    testCompileOnly mn.micronaut.inject.groovy
    testImplementation mnTest.micronaut.test.spock
    testImplementation(projects.testSuiteNatsUtils)
}

tasks.withType(GroovyCompile) {
    groovyOptions.forkOptions.jvmArgs.add('-Dgroovy.parameters=true')
}
